---
title: "SimulationScript"
output: html_document
---

```{r}
pacman::p_load(
  tidyverse,    # Data manipulation and plotting
  here,         # Robust file paths
  cmdstanr,     # Stan interface
  rstan,
  posterior,    # Posterior analysis
  bayesplot,    # Plotting MCMC
  furrr,        # Parallel processing
  future,        # Future backend
  patchwork
)

main_path <- "/Users/mattie/Desktop/Masters/ACM/AdvancedCognitiveModelling/Advanced_Cognitive_Modeling/Assignment04/src/"

setwd(main_path)

```


```{r}
# Parallel Setup: Leave 2 cores free for system stability
n_cores <- parallel::detectCores() - 2
plan(multisession, workers = n_cores)
```

```{r}
# Optional: Set a default ggplot theme
theme_set(theme_classic())
```

# Simulating Data
```{r}
# Flag to control whether to regenerate simulation/fitting results for the knitted files
# Set to TRUE to rerun everything (takes time!), FALSE to load saved results.
regenerate_simulations <- TRUE 

library(tidyverse)
set.seed(42)
```


```{r}
# create 32 stimuli which are 5-dimensional vectors of binary values. Each stimuli should be unique in their binary constallation of the 5 features.

n_stimuli <- 32

stimuli <- expand.grid(
  feature1 = c(0, 1),
  feature2 = c(0, 1),
  feature3 = c(0, 1),
  feature4 = c(0, 1),
  feature5 = c(0, 1)
)
```

```{r}
# Add a stimulus ID for easier reference and two extra binary columns called danger and nutrition

stimuli <- stimuli %>% 
  mutate(
    stimulus_id = row_number(),
    danger = sample(0:1, n_stimuli, replace = TRUE),
    nutrition = sample(0:1, n_stimuli, replace = TRUE)
  )
```

Responses can be 1-4
Response 1 = Not dangerous and not nutritious
